/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package healthconnect;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author joshuatupas
 */
public class JoshuaConnectUI extends javax.swing.JFrame {
    static JoshuaMethods conn = new JoshuaMethods();
    public JoshuaConnectUI() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        medicineCB.setVisible(false);
        dosageCB.setVisible(false);
        medicineLBL.setVisible(false);
        dosageLBL.setVisible(false);
        typeCB.setVisible(false);
        durationCB.setVisible(false);
        typeLBL.setVisible(false);
        durationLBL.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        symptomLBL = new javax.swing.JLabel();
        severityCB = new javax.swing.JComboBox<>();
        medicRB = new javax.swing.JRadioButton();
        therapyRB = new javax.swing.JRadioButton();
        patientLBL = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        submitBTN = new javax.swing.JButton();
        deleteBTN = new javax.swing.JButton();
        moodLBL = new javax.swing.JLabel();
        moodTF = new javax.swing.JTextField();
        severityLBL = new javax.swing.JLabel();
        symptomTF = new javax.swing.JTextField();
        medicineCB = new javax.swing.JComboBox<>();
        typeCB = new javax.swing.JComboBox<>();
        typeLBL = new javax.swing.JLabel();
        durationLBL = new javax.swing.JLabel();
        durationCB = new javax.swing.JComboBox<>();
        medicineLBL = new javax.swing.JLabel();
        dosageCB = new javax.swing.JComboBox<>();
        dosageLBL = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        clearBTN = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        backgroundIMG = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        displayTextArea = new javax.swing.JTextArea();
        viewToggle = new javax.swing.JToggleButton();
        writerBTN = new javax.swing.JButton();
        readerBTN = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 248, 225));

        jTabbedPane1.setBackground(new java.awt.Color(255, 248, 225));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(750, 700));

        jPanel1.setPreferredSize(new java.awt.Dimension(650, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        symptomLBL.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        symptomLBL.setText("Symptom:");
        jPanel1.add(symptomLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        severityCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mild", "Moderate", "Severe", "Extreme" }));
        jPanel1.add(severityCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 180, 40));

        buttonGroup1.add(medicRB);
        medicRB.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        medicRB.setText("Medication");
        medicRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicRBActionPerformed(evt);
            }
        });
        jPanel1.add(medicRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        buttonGroup1.add(therapyRB);
        therapyRB.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        therapyRB.setText("Therapy");
        therapyRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                therapyRBActionPerformed(evt);
            }
        });
        jPanel1.add(therapyRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, -1, -1));

        patientLBL.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        patientLBL.setText("Patient ID:");
        jPanel1.add(patientLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        idTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTFActionPerformed(evt);
            }
        });
        idTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idTFKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idTFKeyTyped(evt);
            }
        });
        jPanel1.add(idTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 180, 40));

        submitBTN.setBackground(new java.awt.Color(192, 222, 255));
        submitBTN.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        submitBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JoshuaImages/add.png"))); // NOI18N
        submitBTN.setText("Submit");
        submitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBTNActionPerformed(evt);
            }
        });
        jPanel1.add(submitBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, 120, 50));

        deleteBTN.setBackground(new java.awt.Color(192, 222, 255));
        deleteBTN.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        deleteBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JoshuaImages/exit.png"))); // NOI18N
        deleteBTN.setText("Delete");
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });
        jPanel1.add(deleteBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, 120, 50));

        moodLBL.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        moodLBL.setText("Current Mood:");
        jPanel1.add(moodLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        moodTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moodTFActionPerformed(evt);
            }
        });
        moodTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                moodTFKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                moodTFKeyTyped(evt);
            }
        });
        jPanel1.add(moodTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 180, 40));

        severityLBL.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        severityLBL.setText("Severity:");
        jPanel1.add(severityLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, -1));

        symptomTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                symptomTFActionPerformed(evt);
            }
        });
        symptomTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                symptomTFKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                symptomTFKeyTyped(evt);
            }
        });
        jPanel1.add(symptomTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 180, 40));

        medicineCB.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        medicineCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Antidepressants", "Antipsychotic", "Anxiolytics", "Lithium", "Stimulants", "Sleeping Pills" }));
        medicineCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicineCBActionPerformed(evt);
            }
        });
        jPanel1.add(medicineCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 160, 40));

        typeCB.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        typeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cognitive Behavioral Therapy", "EMDR Therapy", "Dialectical Behavior Therapy", "Exposure Therapy", "Interpersonal Therapy", "Mentalization-Based Therapy" }));
        jPanel1.add(typeCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 180, 40));

        typeLBL.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        typeLBL.setText("Type:");
        jPanel1.add(typeLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, -1, -1));

        durationLBL.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        durationLBL.setText("Duration:");
        jPanel1.add(durationLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, -1, -1));

        durationCB.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        durationCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "30 mins", "45 mins", "60 mins", "75 mins" }));
        jPanel1.add(durationCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 120, 40));

        medicineLBL.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        medicineLBL.setText("Medicine:");
        jPanel1.add(medicineLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        dosageCB.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        dosageCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3 times a day", "Daily", "Weekly" }));
        jPanel1.add(dosageCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 160, 40));

        dosageLBL.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        dosageLBL.setText("Dosage:");
        jPanel1.add(dosageLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        searchButton.setBackground(new java.awt.Color(192, 222, 255));
        searchButton.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JoshuaImages/Search.png"))); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        jPanel1.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 520, 140, 50));

        clearBTN.setBackground(new java.awt.Color(192, 222, 255));
        clearBTN.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        clearBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JoshuaImages/w.png"))); // NOI18N
        clearBTN.setText("Clear");
        clearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBTNActionPerformed(evt);
            }
        });
        jPanel1.add(clearBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, -1, 50));

        jPanel6.setBackground(new java.awt.Color(255, 248, 225));

        jLabel1.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 24)); // NOI18N
        jLabel1.setText("Mental Health Management");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo_ImgsOne/logo.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(192, 192, 192))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 100));

        backgroundIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JoshuaImages/Mentally Healthy Communities .jpg"))); // NOI18N
        jPanel1.add(backgroundIMG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 580));

        jTabbedPane1.addTab("Mental Health", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        displayTextArea.setColumns(20);
        displayTextArea.setRows(5);
        displayTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                displayTextAreaKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(displayTextArea);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 760, 280));

        viewToggle.setBackground(new java.awt.Color(192, 222, 255));
        viewToggle.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        viewToggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JoshuaImages/folder.png"))); // NOI18N
        viewToggle.setText("View Table");
        viewToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewToggleActionPerformed(evt);
            }
        });
        jPanel2.add(viewToggle, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, -1, 50));

        writerBTN.setBackground(new java.awt.Color(192, 222, 255));
        writerBTN.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        writerBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JoshuaImages/save.png"))); // NOI18N
        writerBTN.setText("File Writer");
        writerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                writerBTNActionPerformed(evt);
            }
        });
        jPanel2.add(writerBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, -1, 50));

        readerBTN.setBackground(new java.awt.Color(192, 222, 255));
        readerBTN.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        readerBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JoshuaImages/job.png"))); // NOI18N
        readerBTN.setText("File Reader");
        readerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readerBTNActionPerformed(evt);
            }
        });
        jPanel2.add(readerBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, -1, 50));

        jPanel5.setBackground(new java.awt.Color(255, 248, 225));

        jLabel3.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 24)); // NOI18N
        jLabel3.setText("Mental Health Details");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo_ImgsOne/logo.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(226, 226, 226))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addContainerGap(36, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JoshuaImages/Mentally Healthy Communities .jpg"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 760, 580));

        jTabbedPane1.addTab("View", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void medicRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicRBActionPerformed

        
        medicineCB.setVisible(true);
        dosageCB.setVisible(true);
        medicineLBL.setVisible(true);
        dosageLBL.setVisible(true);
        typeCB.setVisible(false);
        durationCB.setVisible(false);
        typeLBL.setVisible(false);
        durationLBL.setVisible(false);
    }//GEN-LAST:event_medicRBActionPerformed

    private void therapyRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_therapyRBActionPerformed

        typeCB.setVisible(true);
        durationCB.setVisible(true);
        typeLBL.setVisible(true);
        durationLBL.setVisible(true);
        medicineCB.setVisible(false);
        dosageCB.setVisible(false);
        medicineLBL.setVisible(false);
        dosageLBL.setVisible(false);
    }//GEN-LAST:event_therapyRBActionPerformed

    private void moodTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moodTFActionPerformed

    }//GEN-LAST:event_moodTFActionPerformed

    private void submitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBTNActionPerformed
        String patientId = idTF.getText();
        String currentMood = moodTF.getText();
        String symptom = symptomTF.getText();

        if (patientId.isEmpty() || currentMood.isEmpty() || symptom.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please fill in all fields.");
        } else {
            conn.add();
        }
    }//GEN-LAST:event_submitBTNActionPerformed

    private void symptomTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_symptomTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_symptomTFActionPerformed

    private void medicineCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicineCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicineCBActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        String patientId = idTF.getText();
        if (patientId.isEmpty()) {
            JOptionPane.showMessageDialog(null, "ID must be filled in.");
        } else {
            conn.search();
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        String patientId = idTF.getText();
        if (patientId.isEmpty()) {
            JOptionPane.showMessageDialog(null, "ID must be filled in.");
        } else {
            conn.delete();
        }
    }//GEN-LAST:event_deleteBTNActionPerformed

    private void viewToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewToggleActionPerformed
        conn.display();
    }//GEN-LAST:event_viewToggleActionPerformed

    private void displayTextAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_displayTextAreaKeyTyped
       displayTextArea.setEditable(false);
    }//GEN-LAST:event_displayTextAreaKeyTyped

    private void clearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBTNActionPerformed
        conn.clear();
    }//GEN-LAST:event_clearBTNActionPerformed

    private void writerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_writerBTNActionPerformed
        conn.fileWriter();
    }//GEN-LAST:event_writerBTNActionPerformed

    private void readerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readerBTNActionPerformed
        conn.fileReader();
    }//GEN-LAST:event_readerBTNActionPerformed

    private void idTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTFActionPerformed

    private void idTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTFKeyPressed
        int ID = idTF.getText().length();
        
        if (ID == 4 ) {      
            JOptionPane.showMessageDialog(null,"You cannot type more than 4 numbers");
            idTF.setText(null);
        } 
    }//GEN-LAST:event_idTFKeyPressed

    private void idTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTFKeyTyped
        char copy = evt.getKeyChar();
        
        if (!Character.isDigit(copy)) {
            
            evt.consume();
            
        }
    }//GEN-LAST:event_idTFKeyTyped

    private void moodTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_moodTFKeyPressed
        int letter = moodTF.getText().length();     
        if (letter == 20 ) {            
            JOptionPane.showMessageDialog(null,"You cannot type more than 20 letters");  
            moodTF.setText(null);
        } 
    }//GEN-LAST:event_moodTFKeyPressed

    private void moodTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_moodTFKeyTyped
        char copy = evt.getKeyChar();    
        if (!Character.isLetter(copy)) {         
            evt.consume();           
        }  
    }//GEN-LAST:event_moodTFKeyTyped

    private void symptomTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_symptomTFKeyPressed
        int letter = symptomTF.getText().length();     
        if (letter == 20 ) {            
            JOptionPane.showMessageDialog(null,"You cannot type more than 20 letters");  
            symptomTF.setText(null);
        } 
    }//GEN-LAST:event_symptomTFKeyPressed

    private void symptomTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_symptomTFKeyTyped
        char copy = evt.getKeyChar();      
        if (!Character.isLetter(copy)) {      
            evt.consume();        
        }   
    }//GEN-LAST:event_symptomTFKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JoshuaConnectUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JoshuaConnectUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JoshuaConnectUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JoshuaConnectUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JoshuaConnectUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundIMG;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clearBTN;
    private javax.swing.JButton deleteBTN;
    public static javax.swing.JTextArea displayTextArea;
    public static javax.swing.JComboBox<String> dosageCB;
    private javax.swing.JLabel dosageLBL;
    public static javax.swing.JComboBox<String> durationCB;
    private javax.swing.JLabel durationLBL;
    public static javax.swing.JTextField idTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JRadioButton medicRB;
    public static javax.swing.JComboBox<String> medicineCB;
    private javax.swing.JLabel medicineLBL;
    private javax.swing.JLabel moodLBL;
    public static javax.swing.JTextField moodTF;
    private javax.swing.JLabel patientLBL;
    private javax.swing.JButton readerBTN;
    private javax.swing.JButton searchButton;
    public static javax.swing.JComboBox<String> severityCB;
    private javax.swing.JLabel severityLBL;
    private javax.swing.JButton submitBTN;
    private javax.swing.JLabel symptomLBL;
    public static javax.swing.JTextField symptomTF;
    public static javax.swing.JRadioButton therapyRB;
    public static javax.swing.JComboBox<String> typeCB;
    private javax.swing.JLabel typeLBL;
    private javax.swing.JToggleButton viewToggle;
    private javax.swing.JButton writerBTN;
    // End of variables declaration//GEN-END:variables

}
